--!nocheck

return {
	Slot1 = {
		Stats = {
			Levels = 1,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",

			V9Transfered = false
		},

		Inventory = {},

		QuestsV2 = {
			Main = 1,
			Town = {}
		}
	},
	Slot2 = {
		Stats = {
			Levels = 1,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",

			V9Transfered = false
		},

		Inventory = {},

		QuestsV2 = {
			Main = 1,
			Town = {}
		}
	},
	Slot3 = {
		Stats = {
			Levels = 1,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",

			V9Transfered = false
		},

		Inventory = {},

		QuestsV2 = {
			Main = 1,
			Town = {}
		}
	}
}