--!nocheck

return {
	Slot1 = {
		Stats = {
			Levels = 1,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",
			LastSeenWorld = "Mainworld",
			Cosmetic = "None",

			V9Transfered = false
		},

		Inventory = {},

		QuestsV3 = {
			Main = 1,
			Side = {},
			Town = {}
		}
	},
	Slot2 = {
		Stats = {
			Levels = 1,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",
			LastSeenWorld = "Mainworld",
			Cosmetic = "None",

			V9Transfered = false
		},

		Inventory = {},

		QuestsV3 = {
			Main = 1,
			Side = {},
			Town = {}
		}
	},
	Slot3 = {
		Stats = {
			Levels = 1,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",
			LastSeenWorld = "Mainworld",
			Cosmetic = "None",

			V9Transfered = false
		},

		Inventory = {},

		QuestsV3 = {
			Main = 1,
			Side = {},
			Town = {}
		}
	}
}